{"name": "test_api2[张三-18]", "status": "broken", "statusDetails": {"message": "NameError: name 'yaml_util' is not defined", "trace": "@pytest.fixture(scope=\"session\", autouse=True)\n    def clear_yaml():\n>       yaml_util.YamlUtil().clear_extract_yaml()\nE       NameError: name 'yaml_util' is not defined\n\nconftest.py:14: NameError"}, "parameters": [{"name": "name", "value": "'张三'"}, {"name": "age", "value": "18"}], "start": 1669275394485, "stop": 1669275394485, "uuid": "86dc5a71-0355-4ae5-878e-1f84e380a25a", "historyId": "47393bfab1934db98a729dc4db3ab01c", "testCaseId": "a7b6fe78ffeca118517d048a45bbe491", "fullName": "testcase.test _api.TestApi#test_api2", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test _api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "11572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test _api"}]}