{"name": "test_api2[李四-20]", "status": "broken", "statusDetails": {"message": "NameError: name 'yaml_util' is not defined", "trace": "@pytest.fixture(scope=\"session\", autouse=True)\n    def clear_yaml():\n>       yaml_util.YamlUtil().clear_extract_yaml()\nE       NameError: name 'yaml_util' is not defined\n\nconftest.py:14: NameError"}, "parameters": [{"name": "name", "value": "'李四'"}, {"name": "age", "value": "20"}], "start": 1669275394571, "stop": 1669275394571, "uuid": "a778d433-9afb-4e58-933c-7de84006dcb7", "historyId": "9075763a3e302a4b6d19ce949ac144c8", "testCaseId": "a7b6fe78ffeca118517d048a45bbe491", "fullName": "testcase.test _api.TestApi#test_api2", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test _api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "11572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test _api"}]}